include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unawaited_futures: warning

linter:
  rules:
    - avoid_print
    - unawaited_futures
    - prefer_final_locals
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_declarations
    - always_use_package_imports
    - avoid_catches_without_on_clauses
