-- Admin email notification when a product submission becomes reviewable.
--
-- Delivery does not need to be real-time (confirmed: hourly is fine), so this
-- avoids a trigger on product_submissions -- a table with a documented
-- trigger-ordering incident already -- in favor of a durable outbox row
-- written inside the existing finalize_product_submission RPC, drained later
-- by Supabase Cron. A stuck or failed send never blocks a user's submission:
-- the outbox insert is a plain same-transaction row write, with no outbound
-- HTTP call anywhere near the user-facing RPC.

CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

CREATE TABLE public.admin_submission_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id uuid NOT NULL REFERENCES public.product_submissions(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  attempt_count integer NOT NULL DEFAULT 0,
  last_attempt_at timestamptz,
  last_error text,
  resend_email_id text,
  UNIQUE (submission_id)
);
ALTER TABLE public.admin_submission_notifications ENABLE ROW LEVEL SECURITY;
-- No policies: only SECURITY DEFINER functions below (and service_role) may
-- touch this table, same as product_submission_evidence_revisions.

-- Claims up to p_limit unsent notifications (oldest first) and returns the
-- real, already-known submission fields needed to render the email. Mirrors
-- the FOR UPDATE SKIP LOCKED + stale-claim-reclaim shape already proven in
-- claim_product_submission_cleanup.
CREATE FUNCTION public.claim_admin_submission_notifications(
  p_limit integer DEFAULT 25
)
RETURNS TABLE (
  notification_id bigint,
  submission_id uuid,
  kind public.product_submission_kind,
  normalized_upc text,
  display_name text,
  submitted_at timestamptz,
  is_resubmission boolean,
  photo_count integer,
  extraction_confidence numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 200 THEN
    RAISE EXCEPTION 'invalid notification claim limit' USING ERRCODE = '22023';
  END IF;
  RETURN QUERY
  WITH candidates AS (
    SELECT notification.id
    FROM public.admin_submission_notifications AS notification
    WHERE notification.sent_at IS NULL
      AND notification.attempt_count < 5
      AND (
        notification.claimed_at IS NULL
        OR notification.claimed_at < now() - interval '15 minutes'
      )
    ORDER BY notification.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT p_limit
  ), claimed AS (
    UPDATE public.admin_submission_notifications AS notification
    SET claimed_at = now()
    FROM candidates
    WHERE notification.id = candidates.id
    RETURNING notification.id, notification.submission_id
  )
  SELECT
    claimed.id,
    claimed.submission_id,
    submission.kind,
    submission.normalized_upc,
    submission.display_name,
    submission.submitted_at,
    submission.resubmission_of IS NOT NULL,
    (
      SELECT count(*)::integer
      FROM public.product_submission_photos AS photo
      WHERE photo.submission_id = claimed.submission_id
        AND photo.revision = submission.evidence_revision
    ),
    (
      SELECT extraction.confidence
      FROM public.product_submission_extractions AS extraction
      WHERE extraction.submission_id = claimed.submission_id
      ORDER BY extraction.version DESC
      LIMIT 1
    )
  FROM claimed
  JOIN public.product_submissions AS submission ON submission.id = claimed.submission_id;
END;
$$;
REVOKE ALL ON FUNCTION public.claim_admin_submission_notifications(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_admin_submission_notifications(integer) TO service_role;

-- Records the outcome of one send attempt. On success the row is marked
-- sent and is never claimed again; on failure the claim is released
-- immediately (rather than waiting out the 15-minute staleness window) so
-- the next hourly drain can retry it.
CREATE FUNCTION public.record_admin_submission_notification_result(
  p_notification_id bigint,
  p_success boolean,
  p_resend_email_id text DEFAULT NULL,
  p_error text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_success THEN
    UPDATE public.admin_submission_notifications
    SET sent_at = now(),
        resend_email_id = p_resend_email_id
    WHERE id = p_notification_id;
  ELSE
    UPDATE public.admin_submission_notifications
    SET attempt_count = attempt_count + 1,
        last_attempt_at = now(),
        last_error = left(p_error, 500),
        claimed_at = NULL
    WHERE id = p_notification_id;
  END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.record_admin_submission_notification_result(bigint, boolean, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_admin_submission_notification_result(bigint, boolean, text, text) TO service_role;

-- finalize_product_submission: identical to the version in
-- 20260909013000_submission_foundations_consent_revisions_extraction.sql
-- except for the one INSERT added right before the final RETURN true, once
-- the submission has actually transitioned to upload_state = 'ready'. The
-- early-return "already ready" branch above is untouched, so a duplicate
-- client call never reaches this INSERT a second time; ON CONFLICT DO
-- NOTHING is kept anyway as a second, independent guard.
CREATE OR REPLACE FUNCTION public.finalize_product_submission(
  p_submission_id uuid,
  p_expected_revision integer DEFAULT 1
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  caller_id uuid := auth.uid();
  submission public.product_submissions%ROWTYPE;
  current_revision public.product_submission_evidence_revisions%ROWTYPE;
  manifest jsonb;
BEGIN
  IF caller_id IS NULL THEN
    RAISE EXCEPTION 'authentication required' USING ERRCODE = '42501';
  END IF;

  SELECT candidate.*
    INTO submission
  FROM public.product_submissions AS candidate
  WHERE candidate.id = p_submission_id
    AND candidate.user_id = caller_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'submission not found' USING ERRCODE = '42501';
  END IF;
  IF p_expected_revision IS DISTINCT FROM submission.evidence_revision THEN
    RAISE EXCEPTION 'evidence revision conflict' USING ERRCODE = '55000';
  END IF;
  IF submission.upload_state = 'ready' THEN
    RETURN true;
  END IF;
  IF submission.upload_state <> 'pending' THEN
    RETURN false;
  END IF;

  SELECT revision.*
    INTO current_revision
  FROM public.product_submission_evidence_revisions AS revision
  WHERE revision.submission_id = p_submission_id
    AND revision.revision = submission.evidence_revision
    AND revision.ready_at IS NULL
    AND revision.abandoned_at IS NULL;
  IF NOT FOUND THEN
    RETURN false;
  END IF;
  IF submission.evidence_revision > 1 AND NOT EXISTS (
    SELECT 1
    FROM public.product_submission_photos AS photo
    WHERE photo.submission_id = p_submission_id
      AND photo.revision = submission.evidence_revision
  ) THEN
    RETURN false;
  END IF;

  IF submission.kind = 'missing_product'
     AND NOT public.product_submission_has_required_evidence(
       p_submission_id,
       caller_id
     ) THEN
    RETURN false;
  END IF;
  IF submission.kind = 'label_mismatch' AND NOT EXISTS (
    SELECT 1
    FROM public.product_submission_mismatch_details AS mismatch
    WHERE mismatch.submission_id = p_submission_id
      AND mismatch.user_id = caller_id
  ) THEN
    RETURN false;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.product_submission_photos AS photo
    WHERE photo.submission_id = p_submission_id
      AND photo.user_id = caller_id
      AND photo.photo_id = ANY(current_revision.photo_ids)
      AND NOT EXISTS (
        SELECT 1
        FROM storage.objects AS object
        WHERE object.bucket_id = 'product-submission-photos'
          AND object.owner_id = caller_id::text
          AND object.name = photo.object_path
          AND coalesce((object.metadata->>'size')::bigint, -1)
            = photo.byte_size
          AND lower(coalesce(object.metadata->>'mimetype', ''))
            = photo.content_type
          AND lower(
            coalesce(object.user_metadata->>'content_sha256', '')
          ) = photo.content_sha256
      )
  ) THEN
    RETURN false;
  END IF;

  manifest := public.product_submission_evidence_manifest(
    p_submission_id, submission.evidence_revision
  );
  UPDATE public.product_submission_evidence_revisions
  SET ready_at = now(),
      manifest = public.product_submission_evidence_records(p_submission_id, submission.evidence_revision),
      manifest_sha256 = public.product_submission_manifest_sha256(
        public.product_submission_evidence_records(p_submission_id, submission.evidence_revision))
  WHERE submission_id = p_submission_id
    AND revision = submission.evidence_revision;
  UPDATE public.product_submissions
  SET upload_state = 'ready',
      submitted_at = coalesce(submitted_at, now()),
      evidence_ready_at = now()
  WHERE id = p_submission_id
    AND user_id = caller_id
    AND upload_state = 'pending';

  INSERT INTO public.admin_submission_notifications (submission_id)
  VALUES (p_submission_id)
  ON CONFLICT (submission_id) DO NOTHING;

  RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION public.finalize_product_submission(uuid,integer) FROM PUBLIC, anon, service_role;
GRANT EXECUTE ON FUNCTION public.finalize_product_submission(uuid,integer) TO authenticated;
